version: 1.0.0
name: "Dynamic values and inputs sample"
root:
  threadGroup:
    users: 1
    pacing: 0
    maxDuration: 0
    iterations:
      expression: "someVariable"
    children:
      - callKeyword:
          keyword: "myKeyword"
      - callKeyword:
          keyword:
            expression: "'myKeyword2'"
      - callKeyword:
          keyword: "myKeyword3"
          routing:
           - criteria1: "criteriaValue1"
      - callKeyword:
          keyword:
            expression: "'myKeyword4'"
          routing:
            - criteria1: "criteriaValue1"
          inputs:
            - stringInput:
                expression: "'abc'"
            - intInput: 777