stages:
  - test

variables:
  MAVEN_CLI_OPTS: >-
    --settings settings.xml
    --batch-mode
    --show-version
    --no-transfer-progress

image: maven:3-openjdk-11

cache:
  paths:
    - .m2/repository

test:
  stage: test
  script:
    - 'mvn $MAVEN_CLI_OPTS install'
  artifacts:
    when: always
    paths:
      - junit.xml
    reports:
      junit: junit.xml
